import { type StageDefinition, type Contact, type Task, type Touchpoint } from "./data";

export interface CustomFieldPreset {
  id: string;
  label: string;
  type: "text" | "number" | "date" | "select";
  options?: string[];
}

export interface IndustryPreset {
  id: string;
  name: string;
  description: string;
  icon: string; // lucide icon name key
  stages: StageDefinition[];
  customFields: CustomFieldPreset[];
  contacts: Contact[];
  tasks: Task[];
  touchpoints: Touchpoint[];
  companyName: string;
}

export const industryPresets: IndustryPreset[] = [
  {
    id: "b2b",
    name: "B2B Sales",
    description: "Sell products or services to other businesses. Track leads through qualification, proposals, and negotiations.",
    icon: "building2",
    companyName: "Acme Sales",
    stages: [
      { label: "Lead", color: "text-blue-700", bgColor: "bg-blue-100" },
      { label: "Qualified", color: "text-purple-700", bgColor: "bg-purple-100" },
      { label: "Proposal", color: "text-amber-700", bgColor: "bg-amber-100" },
      { label: "Negotiation", color: "text-orange-700", bgColor: "bg-orange-100" },
      { label: "Closed Won", color: "text-emerald-700", bgColor: "bg-emerald-100" },
      { label: "Closed Lost", color: "text-red-700", bgColor: "bg-red-100" },
    ],
    customFields: [
      { id: "cf-industry", label: "Industry", type: "text" },
      { id: "cf-employees", label: "Employees", type: "select", options: ["1-10", "11-50", "51-200", "201-1000", "1000+"] },
      { id: "cf-source", label: "Lead Source", type: "select", options: ["Inbound", "Outbound", "Referral", "Event", "Partner"] },
    ],
    contacts: [
      { id: "1", name: "Sarah Chen", email: "sarah@voltalabs.com", company: "Volta Labs", role: "Head of Operations", phone: "(415) 555-0142", avatar: "SC", avatarColor: "bg-blue-500", stage: "Proposal", value: 12400, owner: "You", lastContact: "Today", created: "Feb 3, 2026", tags: ["Enterprise", "Q2 Target"] },
      { id: "2", name: "Marcus Rivera", email: "marcus@kineticsupply.com", company: "Kinetic Supply", role: "CEO", phone: "(312) 555-0198", avatar: "MR", avatarColor: "bg-emerald-500", stage: "Qualified", value: 8200, owner: "Lisa", lastContact: "Yesterday", created: "Jan 18, 2026", tags: ["SMB"] },
      { id: "3", name: "Jamie Liu", email: "jamie@nomadfreight.com", company: "Nomad Freight", role: "VP Sales", phone: "(646) 555-0167", avatar: "JL", avatarColor: "bg-violet-500", stage: "Lead", value: 5600, owner: "You", lastContact: "Mar 12", created: "Mar 10, 2026", tags: ["Logistics"] },
      { id: "4", name: "Anika Patel", email: "anika@greenfield.co", company: "Greenfield Co", role: "Founder", phone: "(512) 555-0134", avatar: "AP", avatarColor: "bg-rose-500", stage: "Closed Won", value: 22000, owner: "You", lastContact: "Mar 14", created: "Dec 5, 2025", tags: ["Enterprise", "Referral"] },
      { id: "5", name: "David Kim", email: "david@peakdigital.io", company: "Peak Digital", role: "Director of Sales", phone: "(213) 555-0156", avatar: "DK", avatarColor: "bg-cyan-500", stage: "Negotiation", value: 18500, owner: "Tom", lastContact: "Today", created: "Jan 28, 2026", tags: ["Agency", "Priority"] },
      { id: "6", name: "Rachel Torres", email: "rachel@brightsidehq.com", company: "Brightside HQ", role: "COO", phone: "(305) 555-0189", avatar: "RT", avatarColor: "bg-amber-500", stage: "Lead", value: 6800, owner: "Sarah N.", lastContact: "Mar 15", created: "Mar 14, 2026", tags: ["SMB", "Inbound"] },
      { id: "7", name: "Nathan Brooks", email: "nathan@ironclad.dev", company: "Ironclad Dev", role: "CTO", phone: "(503) 555-0145", avatar: "NB", avatarColor: "bg-indigo-500", stage: "Qualified", value: 14200, owner: "You", lastContact: "Mar 13", created: "Feb 20, 2026", tags: ["Tech", "Enterprise"] },
      { id: "8", name: "Elena Vasquez", email: "elena@suncrestfoods.com", company: "Suncrest Foods", role: "Purchasing Manager", phone: "(602) 555-0178", avatar: "EV", avatarColor: "bg-teal-500", stage: "Proposal", value: 9800, owner: "Tom", lastContact: "Mar 11", created: "Feb 12, 2026", tags: ["F&B"] },
      { id: "9", name: "Chris Adeyemi", email: "chris@mapleconsulting.com", company: "Maple Consulting", role: "Managing Partner", phone: "(416) 555-0123", avatar: "CA", avatarColor: "bg-lime-600", stage: "Lead", value: 4500, owner: "James", lastContact: "Mar 16", created: "Mar 15, 2026", tags: ["Consulting", "Inbound"] },
      { id: "10", name: "Priya Sharma", email: "priya@canvasarch.com", company: "Canvas Architecture", role: "Principal", phone: "(917) 555-0191", avatar: "PS", avatarColor: "bg-pink-500", stage: "Closed Lost", value: 15000, owner: "You", lastContact: "Mar 8", created: "Jan 5, 2026", tags: ["Architecture"] },
      { id: "11", name: "Omar Farah", email: "omar@nextsteplogistics.com", company: "NextStep Logistics", role: "Operations Lead", phone: "(612) 555-0167", avatar: "OF", avatarColor: "bg-sky-500", stage: "Lead", value: 7200, owner: "Sarah N.", lastContact: "Mar 16", created: "Mar 16, 2026", tags: ["Logistics", "Referral"] },
      { id: "12", name: "Megan Hall", email: "megan@firebrandmedia.com", company: "Firebrand Media", role: "Account Director", phone: "(310) 555-0134", avatar: "MH", avatarColor: "bg-fuchsia-500", stage: "Negotiation", value: 11000, owner: "Lisa", lastContact: "Today", created: "Feb 8, 2026", tags: ["Agency", "Q2 Target"] },
    ],
    tasks: [
      { id: "k1", contactId: "1", source: "crm", title: "Send updated proposal to Sarah", description: "Include revised Q2 pricing with volume discount tiers. She wants to present to CFO by end of week.", due: "2026-03-17", owner: "You", completed: false, priority: "high" },
      { id: "k2", contactId: "5", source: "crm", title: "Draft custom SLA for Peak Digital", description: "David requested a custom SLA addendum covering 99.9% uptime and 4-hour response time for critical issues.", due: "2026-03-18", owner: "Tom", completed: false, priority: "high" },
      { id: "k3", contactId: "4", source: "crm", title: "Send onboarding docs to Anika", description: "Share the welcome kit, implementation timeline, and access credentials for the sandbox environment.", due: "2026-03-18", owner: "You", completed: false, priority: "medium" },
      { id: "k4", contactId: "3", source: "crm", title: "Schedule demo for Jamie Liu", description: "Jamie wants to see the team plan features for 8 reps. Coordinate with SE team for a live walkthrough.", due: "2026-03-20", owner: "You", completed: false, priority: "medium" },
      { id: "k5", contactId: "7", source: "crm", title: "Share API documentation with Nathan", description: "Send the REST API docs and webhook integration guide. He needs to verify compatibility with their Node.js stack.", due: "2026-03-19", owner: "You", completed: false, priority: "medium" },
      { id: "k6", contactId: "12", source: "crm", title: "Follow up on revised proposal", description: "Megan's team is reviewing the adjusted scope. Check if they have questions before their internal meeting Friday.", due: "2026-03-21", owner: "Lisa", completed: false, priority: "medium" },
      { id: "k7", contactId: "6", source: "crm", title: "Send intro email to Rachel", description: "Warm intro email with overview of Team plan. She has 25 employees and is growing — good fit for mid-market.", due: "2026-03-14", owner: "Sarah N.", completed: false, priority: "low" },
      { id: "k8", contactId: "2", source: "crm", title: "Check in with Marcus on evaluation", description: "Marcus is comparing us against two competitors. Touch base to see where they are in the decision process.", due: "2026-03-22", owner: "Lisa", completed: false, priority: "low" },
      { id: "k9", contactId: "9", source: "crm", title: "Qualify inbound from Chris", description: "Chris filled out the contact form. Research Maple Consulting and assess fit before scheduling a discovery call.", due: "2026-03-13", owner: "James", completed: false, priority: "low" },
      { id: "k10", contactId: "11", source: "crm", title: "Discovery call with Omar", description: "Initial call to understand NextStep Logistics' needs. They were referred by an existing customer.", due: "2026-03-19", owner: "Sarah N.", completed: false, priority: "medium" },
      { id: "k11", contactId: "8", source: "crm", title: "Prepare demo environment for Suncrest", description: "Set up a 15-seat sandbox with sample data matching their food distribution workflow.", due: "2026-03-15", owner: "Tom", completed: true, priority: "medium" },
      { id: "k12", contactId: "1", source: "crm", title: "Research Volta Labs competitors", description: "Pull together intel on what tools Volta Labs is currently using and who else they might be evaluating.", due: "2026-03-10", owner: "You", completed: true, priority: "low" },
      { id: "k13", contactId: "2", source: "crm", title: "Prep competitive analysis for Marcus", description: "Build a side-by-side comparison highlighting our advantages in integrations and pricing vs. the two competitors.", due: "2026-03-12", owner: "Lisa", completed: false, priority: "high" },
      { id: "k14", contactId: "5", source: "crm", title: "Send case study to David", description: "Share the FinServ case study showing how a similar company reduced onboarding time by 40%.", due: "2026-03-15", owner: "Tom", completed: false, priority: "medium" },
      { id: "k15", contactId: "8", source: "crm", title: "Schedule follow-up call with Elena", description: "Check in after the proposal review. Discuss any customization needs and timeline for implementation.", due: "2026-03-24", owner: "Tom", completed: false, priority: "low" },
      { id: "k16", contactId: "12", source: "crm", title: "Draft SOW for Firebrand Media", description: "Create statement of work based on the revised proposal scope. Include deliverables, timeline, and payment terms.", due: "2026-03-25", owner: "Lisa", completed: false, priority: "high" },
    ],
    touchpoints: [
      { id: "t1", contactId: "1", type: "call", title: "Pricing discussion", description: "Discussed Q2 rollout pricing and volume discount. Sarah wants to loop in CFO next week.", date: "Today, 2:30 PM", owner: "You" },
      { id: "t2", contactId: "5", type: "meeting", title: "Contract review", description: "Walked through contract terms. David requested a custom SLA addendum. Following up Friday.", date: "Today, 11:00 AM", owner: "Tom" },
      { id: "t3", contactId: "12", type: "email", title: "Proposal follow-up", description: "Sent revised proposal with adjusted scope. Megan will review with her team by EOW.", date: "Today, 9:15 AM", owner: "Lisa" },
      { id: "t4", contactId: "2", type: "email", title: "Product comparison", description: "Sent comparison sheet vs. competitors. Marcus is evaluating two other options.", date: "Yesterday, 4:45 PM", owner: "Lisa" },
      { id: "t5", contactId: "4", type: "meeting", title: "Contract sign-off", description: "Final contract review and signature. Anika confirmed annual commitment. Deal closed.", date: "Mar 14, 3:00 PM", owner: "You" },
      { id: "t6", contactId: "7", type: "call", title: "Technical requirements", description: "Nathan outlined their API integration needs. Confirmed we can support their stack.", date: "Mar 13, 10:30 AM", owner: "You" },
      { id: "t7", contactId: "3", type: "call", title: "Discovery call", description: "Initial call with Jamie. Interested in team plan for 8 reps. Wants a demo next week.", date: "Mar 12, 1:00 PM", owner: "You" },
      { id: "t8", contactId: "8", type: "email", title: "Proposal sent", description: "Sent formal proposal for 15-seat deployment with customization scope.", date: "Mar 11, 2:00 PM", owner: "Tom" },
      { id: "t9", contactId: "10", type: "call", title: "Budget constraints", description: "Priya informed us the project has been deprioritized due to budget cuts. Revisit in Q3.", date: "Mar 8, 11:00 AM", owner: "You" },
      { id: "t10", contactId: "6", type: "note", title: "Inbound lead research", description: "Rachel filled out the contact form. Company has 25 employees, growing. Good fit for Team plan.", date: "Mar 15, 9:00 AM", owner: "Sarah N." },
    ],
  },
  {
    id: "saas",
    name: "SaaS",
    description: "Manage software subscriptions and product-led growth. Track users from trial to paid conversion.",
    icon: "monitor",
    companyName: "CloudFlow",
    stages: [
      { label: "Awareness", color: "text-blue-700", bgColor: "bg-blue-100" },
      { label: "Interest", color: "text-cyan-700", bgColor: "bg-cyan-100" },
      { label: "Demo", color: "text-purple-700", bgColor: "bg-purple-100" },
      { label: "Trial", color: "text-amber-700", bgColor: "bg-amber-100" },
      { label: "Negotiation", color: "text-orange-700", bgColor: "bg-orange-100" },
      { label: "Closed Won", color: "text-emerald-700", bgColor: "bg-emerald-100" },
      { label: "Closed Lost", color: "text-red-700", bgColor: "bg-red-100" },
    ],
    customFields: [
      { id: "cf-mrr", label: "MRR", type: "number" },
      { id: "cf-users", label: "Active Users", type: "number" },
      { id: "cf-plan", label: "Plan Type", type: "select", options: ["Free", "Starter", "Pro", "Enterprise"] },
      { id: "cf-source", label: "Signup Source", type: "select", options: ["Organic", "Paid Ad", "Referral", "Product Hunt", "Partner"] },
    ],
    contacts: [
      { id: "1", name: "Alex Turner", email: "alex@streamline.io", company: "Streamline", role: "Head of Product", phone: "(415) 555-0201", avatar: "AT", avatarColor: "bg-blue-500", stage: "Trial", value: 4800, owner: "You", lastContact: "Today", created: "Mar 5, 2026", tags: ["Enterprise", "14-day trial"] },
      { id: "2", name: "Priya Mehta", email: "priya@dataloop.co", company: "DataLoop", role: "VP Engineering", phone: "(650) 555-0134", avatar: "PM", avatarColor: "bg-violet-500", stage: "Demo", value: 12000, owner: "You", lastContact: "Today", created: "Feb 20, 2026", tags: ["Enterprise", "API interest"] },
      { id: "3", name: "Jordan Lee", email: "jordan@pixelcraft.dev", company: "PixelCraft", role: "Founder", phone: "(206) 555-0178", avatar: "JL", avatarColor: "bg-emerald-500", stage: "Awareness", value: 1200, owner: "Lisa", lastContact: "Mar 14", created: "Mar 12, 2026", tags: ["Startup", "Inbound"] },
      { id: "4", name: "Nina Kowalski", email: "nina@formstack.com", company: "FormStack Pro", role: "CTO", phone: "(312) 555-0156", avatar: "NK", avatarColor: "bg-rose-500", stage: "Closed Won", value: 8400, owner: "You", lastContact: "Mar 10", created: "Jan 15, 2026", tags: ["Mid-Market", "Annual"] },
      { id: "5", name: "Ryan Okafor", email: "ryan@boostly.app", company: "Boostly", role: "CEO", phone: "(213) 555-0189", avatar: "RO", avatarColor: "bg-cyan-500", stage: "Negotiation", value: 24000, owner: "Tom", lastContact: "Today", created: "Feb 1, 2026", tags: ["Enterprise", "Multi-seat"] },
      { id: "6", name: "Sam Delgado", email: "sam@launchpad.co", company: "LaunchPad", role: "Growth Lead", phone: "(305) 555-0145", avatar: "SD", avatarColor: "bg-amber-500", stage: "Interest", value: 2400, owner: "Lisa", lastContact: "Mar 15", created: "Mar 13, 2026", tags: ["Startup"] },
      { id: "7", name: "Maya Tanaka", email: "maya@nimbusops.io", company: "NimbusOps", role: "Director of Eng", phone: "(503) 555-0167", avatar: "MT", avatarColor: "bg-indigo-500", stage: "Trial", value: 6000, owner: "You", lastContact: "Mar 12", created: "Mar 1, 2026", tags: ["Mid-Market", "Self-serve"] },
      { id: "8", name: "Carlos Reyes", email: "carlos@fasttrack.io", company: "FastTrack", role: "Product Manager", phone: "(512) 555-0198", avatar: "CR", avatarColor: "bg-teal-500", stage: "Demo", value: 3600, owner: "Tom", lastContact: "Mar 11", created: "Feb 25, 2026", tags: ["SMB"] },
      { id: "9", name: "Emma Walsh", email: "emma@insightiq.com", company: "InsightIQ", role: "COO", phone: "(646) 555-0123", avatar: "EW", avatarColor: "bg-pink-500", stage: "Closed Lost", value: 18000, owner: "You", lastContact: "Mar 6", created: "Dec 10, 2025", tags: ["Enterprise"] },
      { id: "10", name: "Liam Chen", email: "liam@codebase.dev", company: "CodeBase", role: "Lead Developer", phone: "(917) 555-0191", avatar: "LC", avatarColor: "bg-sky-500", stage: "Awareness", value: 1800, owner: "Lisa", lastContact: "Mar 16", created: "Mar 16, 2026", tags: ["Startup", "Dev tools"] },
    ],
    tasks: [
      { id: "k1", contactId: "1", source: "crm", title: "Check trial usage metrics for Streamline", description: "Review seat activation, feature adoption, and daily active users. Alex's team should be near full rollout.", due: "2026-03-17", owner: "You", completed: false, priority: "high" },
      { id: "k2", contactId: "2", source: "crm", title: "Prepare custom demo for DataLoop", description: "Priya needs to see REST and GraphQL API integration. Set up sandbox with their sample data schema.", due: "2026-03-18", owner: "You", completed: false, priority: "high" },
      { id: "k3", contactId: "5", source: "crm", title: "Send enterprise pricing to Ryan", description: "Include multi-year discount options. He's interested in 2-year commitment at 20% off list price.", due: "2026-03-17", owner: "Tom", completed: false, priority: "high" },
      { id: "k4", contactId: "4", source: "crm", title: "Schedule onboarding kickoff with Nina", description: "Annual plan starts April 1. Coordinate with CSM for implementation timeline and training sessions.", due: "2026-03-19", owner: "You", completed: false, priority: "medium" },
      { id: "k5", contactId: "7", source: "crm", title: "Follow up on trial feedback — Maya", description: "Maya's team started trial last week. Check if they attended office hours and identify any blockers.", due: "2026-03-20", owner: "You", completed: false, priority: "medium" },
      { id: "k6", contactId: "6", source: "crm", title: "Send case study to LaunchPad", description: "Share the MarketEdge case study — similar stage startup that saw 3x pipeline growth in 90 days.", due: "2026-03-18", owner: "Lisa", completed: false, priority: "low" },
      { id: "k7", contactId: "8", source: "crm", title: "Demo follow-up with Carlos", description: "Carlos attended the live demo last week. Send recording and address his question about SSO support.", due: "2026-03-21", owner: "Tom", completed: false, priority: "medium" },
      { id: "k8", contactId: "3", source: "crm", title: "Nurture email to Jordan", description: "Jordan went dark after initial interest. Send product update email highlighting new features since last contact.", due: "2026-03-22", owner: "Lisa", completed: false, priority: "low" },
      { id: "k9", contactId: "1", source: "crm", title: "Prepare conversion offer for Streamline", description: "Draft special pricing for trial-to-paid conversion. Include 15% early adopter discount.", due: "2026-03-15", owner: "You", completed: true, priority: "medium" },
      { id: "k10", contactId: "10", source: "crm", title: "Reach out to Liam at CodeBase", description: "Cold outbound — CodeBase recently raised Series A. Good fit for our developer tools tier.", due: "2026-03-19", owner: "Lisa", completed: false, priority: "low" },
    ],
    touchpoints: [
      { id: "t1", contactId: "1", type: "email", title: "Trial check-in", description: "Alex's team has activated 12 of 15 seats. Engagement looks strong — schedule conversion call.", date: "Today, 3:00 PM", owner: "You" },
      { id: "t2", contactId: "5", type: "meeting", title: "Pricing negotiation", description: "Ryan wants multi-year discount. Discussed 20% off for 2-year commitment. Sending revised proposal.", date: "Today, 10:30 AM", owner: "Tom" },
      { id: "t3", contactId: "2", type: "call", title: "Demo prep call", description: "Priya needs API integration demo. Confirmed REST and GraphQL support. Demo Thursday.", date: "Today, 9:00 AM", owner: "You" },
      { id: "t4", contactId: "4", type: "email", title: "Welcome & onboarding", description: "Sent onboarding guide and assigned CSM. Nina confirmed annual plan starts April 1.", date: "Mar 10, 2:00 PM", owner: "You" },
      { id: "t5", contactId: "7", type: "email", title: "Trial activation", description: "Maya's team started trial. Sent best practices guide and offered office hours.", date: "Mar 12, 11:00 AM", owner: "You" },
      { id: "t6", contactId: "8", type: "meeting", title: "Product demo", description: "Showed Carlos the reporting dashboard and integrations. Interested in Zapier connector.", date: "Mar 11, 1:00 PM", owner: "Tom" },
      { id: "t7", contactId: "6", type: "note", title: "Inbound research", description: "Sam signed up after seeing our Product Hunt launch. Growth-stage startup, 15 employees.", date: "Mar 15, 9:00 AM", owner: "Lisa" },
      { id: "t8", contactId: "9", type: "call", title: "Lost deal debrief", description: "Emma said they went with a competitor due to better Salesforce integration. Revisit Q3.", date: "Mar 6, 4:00 PM", owner: "You" },
    ],
  },
  {
    id: "realestate",
    name: "Real Estate",
    description: "Manage property buyers and sellers. Track from initial inquiry through viewings to close.",
    icon: "home",
    companyName: "HomeKey Realty",
    stages: [
      { label: "Inquiry", color: "text-blue-700", bgColor: "bg-blue-100" },
      { label: "Viewing", color: "text-purple-700", bgColor: "bg-purple-100" },
      { label: "Offer", color: "text-amber-700", bgColor: "bg-amber-100" },
      { label: "Under Contract", color: "text-orange-700", bgColor: "bg-orange-100" },
      { label: "Closed Won", color: "text-emerald-700", bgColor: "bg-emerald-100" },
      { label: "Closed Lost", color: "text-red-700", bgColor: "bg-red-100" },
    ],
    customFields: [
      { id: "cf-property", label: "Property Address", type: "text" },
      { id: "cf-type", label: "Property Type", type: "select", options: ["Single Family", "Condo", "Townhouse", "Multi-Family", "Commercial", "Land"] },
      { id: "cf-beds", label: "Bedrooms", type: "number" },
      { id: "cf-sqft", label: "Square Feet", type: "number" },
      { id: "cf-buyerseller", label: "Client Type", type: "select", options: ["Buyer", "Seller", "Both"] },
      { id: "cf-preapproved", label: "Pre-Approved", type: "select", options: ["Yes", "No", "Pending"] },
    ],
    contacts: [
      { id: "1", name: "Jennifer & Mark Thompson", email: "jthompson@gmail.com", company: "—", role: "Buyer", phone: "(512) 555-0142", avatar: "JT", avatarColor: "bg-blue-500", stage: "Viewing", value: 485000, owner: "You", lastContact: "Today", created: "Feb 15, 2026", tags: ["First-time buyer", "Pre-approved"] },
      { id: "2", name: "David Nguyen", email: "david.nguyen@outlook.com", company: "—", role: "Seller", phone: "(415) 555-0198", avatar: "DN", avatarColor: "bg-emerald-500", stage: "Under Contract", value: 725000, owner: "You", lastContact: "Today", created: "Jan 20, 2026", tags: ["Relocation"] },
      { id: "3", name: "Maria Santos", email: "msantos@remax.net", company: "—", role: "Buyer", phone: "(305) 555-0167", avatar: "MS", avatarColor: "bg-violet-500", stage: "Inquiry", value: 350000, owner: "Lisa", lastContact: "Mar 15", created: "Mar 14, 2026", tags: ["Investment property"] },
      { id: "4", name: "Robert & Lisa Chen", email: "rchen@gmail.com", company: "—", role: "Seller", phone: "(213) 555-0134", avatar: "RC", avatarColor: "bg-rose-500", stage: "Closed Won", value: 890000, owner: "You", lastContact: "Mar 10", created: "Nov 5, 2025", tags: ["Luxury", "Repeat client"] },
      { id: "5", name: "Amanda Foster", email: "afoster@yahoo.com", company: "Foster Properties LLC", role: "Investor", phone: "(646) 555-0156", avatar: "AF", avatarColor: "bg-cyan-500", stage: "Offer", value: 1200000, owner: "Tom", lastContact: "Today", created: "Feb 1, 2026", tags: ["Multi-family", "Cash offer"] },
      { id: "6", name: "James Park", email: "jpark@outlook.com", company: "—", role: "Buyer", phone: "(312) 555-0189", avatar: "JP", avatarColor: "bg-amber-500", stage: "Inquiry", value: 275000, owner: "Lisa", lastContact: "Mar 16", created: "Mar 16, 2026", tags: ["Condo", "Downtown"] },
      { id: "7", name: "Sarah Mitchell", email: "smitchell@gmail.com", company: "—", role: "Seller", phone: "(503) 555-0145", avatar: "SM", avatarColor: "bg-indigo-500", stage: "Viewing", value: 560000, owner: "You", lastContact: "Mar 13", created: "Feb 28, 2026", tags: ["Open house scheduled"] },
      { id: "8", name: "Carlos & Ana Rodriguez", email: "crodriguez@gmail.com", company: "—", role: "Buyer", phone: "(602) 555-0178", avatar: "CR", avatarColor: "bg-teal-500", stage: "Offer", value: 415000, owner: "Tom", lastContact: "Mar 12", created: "Feb 10, 2026", tags: ["Pre-approved", "Family home"] },
      { id: "9", name: "Patricia Williams", email: "pwilliams@aol.com", company: "—", role: "Seller", phone: "(917) 555-0123", avatar: "PW", avatarColor: "bg-pink-500", stage: "Closed Lost", value: 650000, owner: "You", lastContact: "Mar 5", created: "Jan 10, 2026", tags: ["Withdrew listing"] },
      { id: "10", name: "Michael Chang", email: "mchang@gmail.com", company: "Chang Development", role: "Developer", phone: "(310) 555-0191", avatar: "MC", avatarColor: "bg-sky-500", stage: "Inquiry", value: 2100000, owner: "Tom", lastContact: "Mar 16", created: "Mar 15, 2026", tags: ["Commercial", "New build"] },
    ],
    tasks: [
      { id: "k1", contactId: "1", source: "crm", title: "Schedule 2nd viewing — 45 Oak Lane", description: "Jennifer and Mark want to revisit on Saturday. Confirm with seller's agent and arrange access.", due: "2026-03-17", owner: "You", completed: false, priority: "high" },
      { id: "k2", contactId: "2", source: "crm", title: "Coordinate home inspection", description: "Book certified inspector for the property. Inspection contingency deadline is March 25 — don't delay.", due: "2026-03-18", owner: "You", completed: false, priority: "high" },
      { id: "k3", contactId: "5", source: "crm", title: "Submit counter-offer for Amanda", description: "Amanda's max is $1.18M on the 4-plex. Seller countered at $1.22M. Prepare counter with escalation clause.", due: "2026-03-17", owner: "Tom", completed: false, priority: "high" },
      { id: "k4", contactId: "7", source: "crm", title: "Prepare open house materials", description: "88 Pine Road open house this weekend. Print flyers, update listing photos, and coordinate staging crew.", due: "2026-03-19", owner: "You", completed: false, priority: "medium" },
      { id: "k5", contactId: "8", source: "crm", title: "Follow up on mortgage approval — Rodriguez", description: "Carlos submitted loan docs last week. Check with lender on pre-approval status before showing more homes.", due: "2026-03-20", owner: "Tom", completed: false, priority: "medium" },
      { id: "k6", contactId: "3", source: "crm", title: "Send MLS listings to Maria", description: "Pull new listings in the $650K-$800K range near Westlake. She prefers 3+ beds with a home office.", due: "2026-03-18", owner: "Lisa", completed: false, priority: "medium" },
      { id: "k7", contactId: "6", source: "crm", title: "Pre-qualification check for James", description: "James wants to start looking at investment properties. Needs to get pre-qualified for $500K-$700K range.", due: "2026-03-19", owner: "Lisa", completed: false, priority: "low" },
      { id: "k8", contactId: "10", source: "crm", title: "Pull commercial zoning report", description: "Robert needs zoning classification and permitted uses for the warehouse district property.", due: "2026-03-20", owner: "Tom", completed: false, priority: "medium" },
      { id: "k9", contactId: "4", source: "crm", title: "Send closing gift to Chen family", description: "Closed on 120 Elm St. Order a personalized cutting board and welcome basket for delivery this week.", due: "2026-03-14", owner: "You", completed: true, priority: "low" },
      { id: "k10", contactId: "2", source: "crm", title: "Review appraisal report for Nguyen", description: "Appraisal came in — need to review and compare against offer price. May need to renegotiate if low.", due: "2026-03-22", owner: "You", completed: false, priority: "high" },
    ],
    touchpoints: [
      { id: "t1", contactId: "1", type: "meeting", title: "Property viewing — 45 Oak Lane", description: "Jennifer and Mark loved the backyard and kitchen. Concerned about school district. Want a 2nd viewing.", date: "Today, 2:00 PM", owner: "You" },
      { id: "t2", contactId: "5", type: "call", title: "Offer negotiation", description: "Amanda offering $1.15M on the 4-plex. Seller countered at $1.22M. She may go to $1.18M.", date: "Today, 10:00 AM", owner: "Tom" },
      { id: "t3", contactId: "2", type: "email", title: "Contract update", description: "Sent inspection contingency deadlines. David confirmed he'll have repairs done by March 25.", date: "Today, 9:30 AM", owner: "You" },
      { id: "t4", contactId: "4", type: "meeting", title: "Closing day", description: "Closed on 120 Elm Street. Final price $890,000. Keys handed over. Celebrated with champagne!", date: "Mar 10, 3:00 PM", owner: "You" },
      { id: "t5", contactId: "7", type: "note", title: "Listing prep", description: "Sarah's home at 88 Pine Road needs staging. Photographer booked for Thursday. Target list price $560K.", date: "Mar 13, 11:00 AM", owner: "You" },
      { id: "t6", contactId: "8", type: "call", title: "Offer submitted", description: "Carlos and Ana submitted offer at $415K on 22 Maple Drive. Awaiting seller response by EOD Friday.", date: "Mar 12, 4:00 PM", owner: "Tom" },
      { id: "t7", contactId: "6", type: "email", title: "New inquiry follow-up", description: "James interested in downtown condos, $250-300K range. Sent 5 active listings for review.", date: "Mar 16, 10:00 AM", owner: "Lisa" },
      { id: "t8", contactId: "9", type: "call", title: "Listing withdrawn", description: "Patricia decided not to sell after all. Personal circumstances changed. Will revisit in 6 months.", date: "Mar 5, 2:00 PM", owner: "You" },
    ],
  },
  {
    id: "recruiting",
    name: "Recruiting",
    description: "Track candidates through your hiring pipeline. Manage interviews, offers, and placements.",
    icon: "usersRound",
    companyName: "TalentBridge",
    stages: [
      { label: "Applied", color: "text-blue-700", bgColor: "bg-blue-100" },
      { label: "Phone Screen", color: "text-cyan-700", bgColor: "bg-cyan-100" },
      { label: "Interview", color: "text-purple-700", bgColor: "bg-purple-100" },
      { label: "Final Round", color: "text-amber-700", bgColor: "bg-amber-100" },
      { label: "Offer", color: "text-orange-700", bgColor: "bg-orange-100" },
      { label: "Hired", color: "text-emerald-700", bgColor: "bg-emerald-100" },
      { label: "Rejected", color: "text-red-700", bgColor: "bg-red-100" },
    ],
    customFields: [
      { id: "cf-position", label: "Position", type: "text" },
      { id: "cf-experience", label: "Years Experience", type: "number" },
      { id: "cf-salary", label: "Salary Expectation", type: "number" },
      { id: "cf-location", label: "Location Pref", type: "select", options: ["Remote", "Hybrid", "On-site", "Flexible"] },
      { id: "cf-notice", label: "Notice Period", type: "select", options: ["Immediate", "2 weeks", "1 month", "2 months", "3 months"] },
    ],
    contacts: [
      { id: "1", name: "Emily Zhang", email: "emily.zhang@gmail.com", company: "Ex-Google", role: "Senior Engineer", phone: "(415) 555-0201", avatar: "EZ", avatarColor: "bg-blue-500", stage: "Final Round", value: 165000, owner: "You", lastContact: "Today", created: "Feb 25, 2026", tags: ["Senior", "Frontend"] },
      { id: "2", name: "James Okonkwo", email: "jokonkwo@outlook.com", company: "Ex-Meta", role: "Product Manager", phone: "(646) 555-0134", avatar: "JO", avatarColor: "bg-emerald-500", stage: "Interview", value: 185000, owner: "Lisa", lastContact: "Today", created: "Mar 1, 2026", tags: ["Senior", "Product"] },
      { id: "3", name: "Sofia Petrov", email: "spetrov@proton.me", company: "Ex-Stripe", role: "Backend Engineer", phone: "(312) 555-0167", avatar: "SP", avatarColor: "bg-violet-500", stage: "Phone Screen", value: 155000, owner: "You", lastContact: "Mar 15", created: "Mar 12, 2026", tags: ["Mid-level", "Backend"] },
      { id: "4", name: "Daniel Kim", email: "dkim@gmail.com", company: "Ex-Amazon", role: "Engineering Manager", phone: "(206) 555-0156", avatar: "DK", avatarColor: "bg-rose-500", stage: "Hired", value: 210000, owner: "You", lastContact: "Mar 10", created: "Jan 15, 2026", tags: ["Leadership", "Backend"] },
      { id: "5", name: "Ava Morales", email: "amorales@yahoo.com", company: "Ex-Netflix", role: "Data Scientist", phone: "(213) 555-0189", avatar: "AM", avatarColor: "bg-cyan-500", stage: "Offer", value: 175000, owner: "Tom", lastContact: "Today", created: "Feb 10, 2026", tags: ["Senior", "ML/AI"] },
      { id: "6", name: "Tyler Johnson", email: "tjohnson@gmail.com", company: "Bootcamp grad", role: "Junior Developer", phone: "(305) 555-0145", avatar: "TJ", avatarColor: "bg-amber-500", stage: "Applied", value: 85000, owner: "Lisa", lastContact: "Mar 16", created: "Mar 16, 2026", tags: ["Junior", "Frontend"] },
      { id: "7", name: "Nisha Gupta", email: "nisha.g@outlook.com", company: "Ex-Shopify", role: "Designer", phone: "(503) 555-0178", avatar: "NG", avatarColor: "bg-indigo-500", stage: "Interview", value: 140000, owner: "You", lastContact: "Mar 13", created: "Mar 3, 2026", tags: ["Senior", "UX/UI"] },
      { id: "8", name: "Marcus Brown", email: "mbrown@gmail.com", company: "Ex-Microsoft", role: "DevOps Engineer", phone: "(512) 555-0198", avatar: "MB", avatarColor: "bg-teal-500", stage: "Phone Screen", value: 160000, owner: "Tom", lastContact: "Mar 14", created: "Mar 10, 2026", tags: ["Mid-level", "Infrastructure"] },
      { id: "9", name: "Olivia Davis", email: "odavis@proton.me", company: "Ex-Uber", role: "Product Designer", phone: "(917) 555-0123", avatar: "OD", avatarColor: "bg-pink-500", stage: "Rejected", value: 130000, owner: "You", lastContact: "Mar 8", created: "Feb 5, 2026", tags: ["Mid-level", "Mobile"] },
      { id: "10", name: "Ryan Sato", email: "rsato@gmail.com", company: "Ex-Apple", role: "iOS Engineer", phone: "(650) 555-0191", avatar: "RS", avatarColor: "bg-sky-500", stage: "Applied", value: 180000, owner: "Lisa", lastContact: "Mar 16", created: "Mar 15, 2026", tags: ["Senior", "Mobile"] },
    ],
    tasks: [
      { id: "k1", contactId: "1", source: "crm", title: "Schedule final panel interview — Emily", description: "Emily passed the technical round unanimously. Set up panel with VP Eng and CTO for Thursday or Friday.", due: "2026-03-17", owner: "You", completed: false, priority: "high" },
      { id: "k2", contactId: "5", source: "crm", title: "Send offer letter to Ava", description: "Offer: $165K base + RSUs, remote flexibility. Get final approval from hiring manager before sending.", due: "2026-03-17", owner: "Tom", completed: false, priority: "high" },
      { id: "k3", contactId: "2", source: "crm", title: "Prep case study for James's interview", description: "James needs a product strategy case study for round 2. Use the marketplace growth scenario.", due: "2026-03-18", owner: "Lisa", completed: false, priority: "high" },
      { id: "k4", contactId: "3", source: "crm", title: "Phone screen with Sofia", description: "30-min screen to assess culture fit and salary expectations. She's currently at a competitor.", due: "2026-03-18", owner: "You", completed: false, priority: "medium" },
      { id: "k5", contactId: "7", source: "crm", title: "Design challenge review — Nisha", description: "Review Nisha's design challenge submission. Evaluate UX thinking, visual polish, and presentation skills.", due: "2026-03-19", owner: "You", completed: false, priority: "medium" },
      { id: "k6", contactId: "8", source: "crm", title: "Schedule phone screen — Marcus", description: "Marcus applied for the DevOps role. 7 years experience, strong AWS background. Screen this week.", due: "2026-03-19", owner: "Tom", completed: false, priority: "medium" },
      { id: "k7", contactId: "6", source: "crm", title: "Review Tyler's coding assessment", description: "Tyler submitted the take-home challenge. Review code quality, test coverage, and architecture decisions.", due: "2026-03-20", owner: "Lisa", completed: false, priority: "low" },
      { id: "k8", contactId: "4", source: "crm", title: "Send Day 1 welcome package to Daniel", description: "Daniel starts March 24. Ship laptop, set up accounts, send welcome guide and first-week schedule.", due: "2026-03-14", owner: "You", completed: true, priority: "medium" },
      { id: "k9", contactId: "10", source: "crm", title: "Resume review — Ryan Sato", description: "Ryan was referred by an engineer on the team. Review resume and portfolio for the frontend role.", due: "2026-03-18", owner: "Lisa", completed: false, priority: "medium" },
      { id: "k10", contactId: "5", source: "crm", title: "Reference check for Ava", description: "Contact Ava's two references — former manager and tech lead. Focus on collaboration and ownership.", due: "2026-03-15", owner: "Tom", completed: true, priority: "high" },
    ],
    touchpoints: [
      { id: "t1", contactId: "1", type: "meeting", title: "Technical interview", description: "Emily aced the system design round. Team unanimously positive. Moving to final panel.", date: "Today, 2:30 PM", owner: "You" },
      { id: "t2", contactId: "5", type: "call", title: "Offer discussion", description: "Ava excited about the role. Wants remote flexibility and RSUs. Sending formal offer letter.", date: "Today, 11:00 AM", owner: "Tom" },
      { id: "t3", contactId: "2", type: "meeting", title: "1st round interview", description: "James showed strong product sense. Good culture fit. Needs case study for round 2.", date: "Today, 9:00 AM", owner: "Lisa" },
      { id: "t4", contactId: "4", type: "email", title: "Offer accepted!", description: "Daniel accepted the EM role. Start date March 24. Comp: $210K base + equity.", date: "Mar 10, 4:00 PM", owner: "You" },
      { id: "t5", contactId: "7", type: "meeting", title: "Portfolio review", description: "Nisha presented impressive case studies. Figma proficiency is excellent. Design challenge next.", date: "Mar 13, 1:00 PM", owner: "You" },
      { id: "t6", contactId: "8", type: "email", title: "Resume received", description: "Marcus has 5 years DevOps experience, strong K8s and AWS background. Scheduling phone screen.", date: "Mar 14, 10:00 AM", owner: "Tom" },
      { id: "t7", contactId: "9", type: "call", title: "Rejection feedback", description: "Informed Olivia — great skills but looking for more mobile-native experience. Encouraged to reapply.", date: "Mar 8, 3:00 PM", owner: "You" },
      { id: "t8", contactId: "3", type: "email", title: "Application review", description: "Sofia's background at Stripe is impressive. 4 years backend, Go and Rust experience. Phone screen booked.", date: "Mar 15, 9:00 AM", owner: "You" },
    ],
  },
  {
    id: "consulting",
    name: "Consulting",
    description: "Win and manage consulting engagements. From discovery to proposal to active engagement.",
    icon: "clipboardList",
    companyName: "Apex Advisors",
    stages: [
      { label: "Discovery", color: "text-blue-700", bgColor: "bg-blue-100" },
      { label: "Scoping", color: "text-purple-700", bgColor: "bg-purple-100" },
      { label: "Proposal", color: "text-amber-700", bgColor: "bg-amber-100" },
      { label: "SOW Review", color: "text-orange-700", bgColor: "bg-orange-100" },
      { label: "Engaged", color: "text-emerald-700", bgColor: "bg-emerald-100" },
    ],
    customFields: [
      { id: "cf-project", label: "Project Type", type: "select", options: ["Strategy", "Operations", "Technology", "Change Management", "Financial Advisory"] },
      { id: "cf-duration", label: "Engagement Length", type: "select", options: ["2 weeks", "1 month", "3 months", "6 months", "12 months+"] },
      { id: "cf-dayrate", label: "Day Rate", type: "number" },
      { id: "cf-team", label: "Team Size", type: "number" },
    ],
    contacts: [
      { id: "1", name: "Victoria Hayes", email: "vhayes@meridian.com", company: "Meridian Corp", role: "VP Strategy", phone: "(212) 555-0142", avatar: "VH", avatarColor: "bg-blue-500", stage: "SOW Review", value: 180000, owner: "You", lastContact: "Today", created: "Feb 10, 2026", tags: ["Strategy", "Q2"] },
      { id: "2", name: "Richard Tan", email: "rtan@oakcapital.com", company: "Oak Capital", role: "Managing Director", phone: "(415) 555-0198", avatar: "RT", avatarColor: "bg-emerald-500", stage: "Proposal", value: 95000, owner: "Lisa", lastContact: "Today", created: "Feb 25, 2026", tags: ["Financial", "Repeat"] },
      { id: "3", name: "Diane Kowalski", email: "dkowalski@nexgen.io", company: "NexGen Solutions", role: "CEO", phone: "(312) 555-0167", avatar: "DK", avatarColor: "bg-violet-500", stage: "Discovery", value: 120000, owner: "You", lastContact: "Mar 15", created: "Mar 13, 2026", tags: ["Technology", "Digital transformation"] },
      { id: "4", name: "Thomas Grant", email: "tgrant@blueridge.co", company: "Blue Ridge Industries", role: "COO", phone: "(704) 555-0134", avatar: "TG", avatarColor: "bg-rose-500", stage: "Engaged", value: 250000, owner: "You", lastContact: "Mar 14", created: "Dec 1, 2025", tags: ["Operations", "Manufacturing"] },
      { id: "5", name: "Sandra Liu", email: "sliu@pacifichealth.org", company: "Pacific Health", role: "Chief of Staff", phone: "(503) 555-0156", avatar: "SL", avatarColor: "bg-cyan-500", stage: "Scoping", value: 200000, owner: "Tom", lastContact: "Mar 14", created: "Mar 1, 2026", tags: ["Healthcare", "Change mgmt"] },
      { id: "6", name: "Peter Nkomo", email: "pnkomo@zenithbank.com", company: "Zenith Bank", role: "Head of Ops", phone: "(646) 555-0189", avatar: "PN", avatarColor: "bg-amber-500", stage: "Discovery", value: 150000, owner: "Lisa", lastContact: "Mar 16", created: "Mar 15, 2026", tags: ["Banking", "Process improvement"] },
      { id: "7", name: "Catherine Bell", email: "cbell@summit.edu", company: "Summit University", role: "Provost", phone: "(617) 555-0145", avatar: "CB", avatarColor: "bg-indigo-500", stage: "Proposal", value: 85000, owner: "You", lastContact: "Mar 13", created: "Feb 28, 2026", tags: ["Education", "Strategic planning"] },
      { id: "8", name: "Andrew Martinez", email: "amartinez@greenleaf.co", company: "GreenLeaf Energy", role: "Director of Ops", phone: "(512) 555-0178", avatar: "AM", avatarColor: "bg-teal-500", stage: "Scoping", value: 175000, owner: "Tom", lastContact: "Mar 12", created: "Mar 5, 2026", tags: ["Energy", "Sustainability"] },
    ],
    tasks: [
      { id: "k1", contactId: "1", source: "crm", title: "Revise SOW based on Victoria's feedback", description: "Victoria wants to add a data analytics workstream. Update scope, timeline, and pricing accordingly.", due: "2026-03-17", owner: "You", completed: false, priority: "high" },
      { id: "k2", contactId: "5", source: "crm", title: "Draft engagement scope for Pacific Health", description: "4 workstreams identified in scoping workshop. Draft initial scope for change management engagement.", due: "2026-03-18", owner: "Tom", completed: false, priority: "high" },
      { id: "k3", contactId: "2", source: "crm", title: "Send proposal deck to Richard", description: "12-week financial advisory proposal at $95K fixed fee. Include team bios and relevant case studies.", due: "2026-03-17", owner: "Lisa", completed: false, priority: "high" },
      { id: "k4", contactId: "3", source: "crm", title: "Discovery session with NexGen team", description: "Half-day workshop to map current state processes. Bring the digital maturity assessment framework.", due: "2026-03-19", owner: "You", completed: false, priority: "medium" },
      { id: "k5", contactId: "4", source: "crm", title: "Monthly progress report — Blue Ridge", description: "Summarize Phase 1 findings: 18% cost reduction identified across 3 departments. Include next steps for Phase 2.", due: "2026-03-20", owner: "You", completed: false, priority: "medium" },
      { id: "k6", contactId: "7", source: "crm", title: "Finalize pricing for Summit engagement", description: "6-week strategic planning engagement with 2-person team. Calculate blended rate and travel costs.", due: "2026-03-18", owner: "You", completed: false, priority: "medium" },
      { id: "k7", contactId: "8", source: "crm", title: "Site visit to GreenLeaf facility", description: "Tour the manufacturing floor and interview department heads. Assess operational efficiency opportunities.", due: "2026-03-21", owner: "Tom", completed: false, priority: "medium" },
      { id: "k8", contactId: "6", source: "crm", title: "Initial call with Peter at Zenith", description: "Peter reached out about strategy consulting. Zenith is a $50M manufacturer looking to expand into new markets.", due: "2026-03-19", owner: "Lisa", completed: false, priority: "low" },
      { id: "k9", contactId: "4", source: "crm", title: "Review Q1 deliverables — Blue Ridge", description: "Final review of Phase 1 deliverables before client presentation. Ensure all recommendations are data-backed.", due: "2026-03-14", owner: "You", completed: true, priority: "high" },
    ],
    touchpoints: [
      { id: "t1", contactId: "1", type: "meeting", title: "SOW walkthrough", description: "Reviewed scope with Victoria. She wants to add a data analytics workstream. Adjusting SOW and pricing.", date: "Today, 2:00 PM", owner: "You" },
      { id: "t2", contactId: "2", type: "email", title: "Proposal sent", description: "Sent 12-week financial advisory proposal. $95K fixed fee. Richard reviewing with board this week.", date: "Today, 10:00 AM", owner: "Lisa" },
      { id: "t3", contactId: "5", type: "meeting", title: "Scoping workshop", description: "2-hour workshop with Pacific Health leadership. Identified 4 key workstreams for change management.", date: "Mar 14, 1:00 PM", owner: "Tom" },
      { id: "t4", contactId: "4", type: "meeting", title: "Sprint review", description: "Presented ops efficiency findings. 18% cost reduction identified. Thomas very pleased. Phase 2 likely.", date: "Mar 14, 10:00 AM", owner: "You" },
      { id: "t5", contactId: "3", type: "call", title: "Discovery call", description: "Diane wants digital transformation roadmap. 200 employees, legacy systems. Complex but high potential.", date: "Mar 15, 3:00 PM", owner: "You" },
      { id: "t6", contactId: "7", type: "email", title: "Proposal draft", description: "Sent initial proposal for strategic planning engagement. 6-week timeline, 2-person team.", date: "Mar 13, 2:00 PM", owner: "You" },
      { id: "t7", contactId: "8", type: "call", title: "Intro call", description: "Andrew wants help with sustainability reporting and operational efficiency. Scheduling site visit.", date: "Mar 12, 11:00 AM", owner: "Tom" },
    ],
  },
  {
    id: "services",
    name: "Home Services",
    description: "Manage service calls and jobs for plumbing, electrical, HVAC, and more. Track from inquiry to completion.",
    icon: "wrench",
    companyName: "ProFix Services",
    stages: [
      { label: "New Lead", color: "text-blue-700", bgColor: "bg-blue-100" },
      { label: "Estimate Sent", color: "text-purple-700", bgColor: "bg-purple-100" },
      { label: "Scheduled", color: "text-amber-700", bgColor: "bg-amber-100" },
      { label: "In Progress", color: "text-orange-700", bgColor: "bg-orange-100" },
      { label: "Completed", color: "text-emerald-700", bgColor: "bg-emerald-100" },
      { label: "Cancelled", color: "text-red-700", bgColor: "bg-red-100" },
    ],
    customFields: [
      { id: "cf-service", label: "Service Type", type: "select", options: ["Plumbing", "Electrical", "HVAC", "Roofing", "General Repair", "Remodel"] },
      { id: "cf-address", label: "Job Address", type: "text" },
      { id: "cf-property", label: "Property Type", type: "select", options: ["Residential", "Commercial", "Multi-family", "HOA"] },
      { id: "cf-urgency", label: "Urgency", type: "select", options: ["Emergency", "Urgent", "Standard", "Flexible"] },
      { id: "cf-hours", label: "Estimated Hours", type: "number" },
    ],
    contacts: [
      { id: "1", name: "Karen Mitchell", email: "karen.m@gmail.com", company: "—", role: "Homeowner", phone: "(512) 555-0142", avatar: "KM", avatarColor: "bg-blue-500", stage: "Scheduled", value: 2800, owner: "You", lastContact: "Today", created: "Mar 10, 2026", tags: ["Plumbing", "Repeat customer"] },
      { id: "2", name: "James & Paula Wright", email: "jwright@outlook.com", company: "—", role: "Homeowner", phone: "(415) 555-0198", avatar: "JW", avatarColor: "bg-emerald-500", stage: "In Progress", value: 4500, owner: "You", lastContact: "Today", created: "Mar 5, 2026", tags: ["Electrical", "Panel upgrade"] },
      { id: "3", name: "Dave Kowalski", email: "davek@yahoo.com", company: "Kowalski Properties", role: "Property Manager", phone: "(312) 555-0167", avatar: "DK", avatarColor: "bg-violet-500", stage: "Estimate Sent", value: 6200, owner: "Lisa", lastContact: "Mar 15", created: "Mar 13, 2026", tags: ["HVAC", "Commercial"] },
      { id: "4", name: "Maria Santos", email: "msantos@gmail.com", company: "—", role: "Homeowner", phone: "(305) 555-0134", avatar: "MS", avatarColor: "bg-rose-500", stage: "Completed", value: 1200, owner: "You", lastContact: "Mar 12", created: "Feb 20, 2026", tags: ["Plumbing", "Fixture install"] },
      { id: "5", name: "Robert Chen", email: "rchen@gmail.com", company: "Oakwood HOA", role: "HOA President", phone: "(213) 555-0156", avatar: "RC", avatarColor: "bg-cyan-500", stage: "Estimate Sent", value: 8500, owner: "Tom", lastContact: "Mar 14", created: "Mar 8, 2026", tags: ["Roofing", "Multi-unit"] },
      { id: "6", name: "Tamara Bell", email: "tbell@outlook.com", company: "—", role: "Homeowner", phone: "(646) 555-0189", avatar: "TB", avatarColor: "bg-amber-500", stage: "New Lead", value: 950, owner: "Lisa", lastContact: "Mar 16", created: "Mar 16, 2026", tags: ["General Repair", "Deck"] },
      { id: "7", name: "Mike Okafor", email: "mokafor@gmail.com", company: "—", role: "Homeowner", phone: "(503) 555-0145", avatar: "MO", avatarColor: "bg-indigo-500", stage: "Scheduled", value: 3200, owner: "You", lastContact: "Mar 13", created: "Mar 6, 2026", tags: ["HVAC", "AC install"] },
      { id: "8", name: "Linda & Steve Park", email: "lpark@gmail.com", company: "—", role: "Homeowner", phone: "(602) 555-0178", avatar: "LP", avatarColor: "bg-teal-500", stage: "New Lead", value: 15000, owner: "Tom", lastContact: "Mar 15", created: "Mar 15, 2026", tags: ["Remodel", "Kitchen"] },
      { id: "9", name: "Greg Hoffman", email: "ghoffman@aol.com", company: "—", role: "Homeowner", phone: "(917) 555-0123", avatar: "GH", avatarColor: "bg-pink-500", stage: "Cancelled", value: 1800, owner: "You", lastContact: "Mar 8", created: "Feb 15, 2026", tags: ["Electrical"] },
      { id: "10", name: "Nancy Torres", email: "ntorres@gmail.com", company: "Sunrise Apartments", role: "Building Manager", phone: "(310) 555-0191", avatar: "NT", avatarColor: "bg-sky-500", stage: "In Progress", value: 3800, owner: "Lisa", lastContact: "Mar 16", created: "Mar 2, 2026", tags: ["Plumbing", "Multi-unit"] },
    ],
    tasks: [
      { id: "k1", contactId: "1", source: "crm", title: "Pick up parts for Karen's bathroom refit", description: "Need low-flow fixtures, shut-off valve, and PEX fittings from supply house. Job starts Thursday 9 AM.", due: "2026-03-17", owner: "You", completed: false, priority: "high" },
      { id: "k2", contactId: "2", source: "crm", title: "Finish panel upgrade — Wright residence", description: "Old 100A panel removed, new 200A mounted. Complete wiring runs tomorrow, schedule inspection for Friday.", due: "2026-03-17", owner: "You", completed: false, priority: "high" },
      { id: "k3", contactId: "3", source: "crm", title: "Send revised HVAC estimate to Dave", description: "3 rooftop units need replacement. Revise quote to include 10-year warranty option and financing terms.", due: "2026-03-18", owner: "Lisa", completed: false, priority: "high" },
      { id: "k4", contactId: "5", source: "crm", title: "Schedule roof inspection — Oakwood HOA", description: "8-unit complex needs roof assessment. Coordinate access with property manager for morning hours.", due: "2026-03-19", owner: "Tom", completed: false, priority: "medium" },
      { id: "k5", contactId: "7", source: "crm", title: "Confirm AC unit delivery for Mike", description: "3-ton Carrier unit ordered. Verify delivery date and schedule install crew for the following day.", due: "2026-03-18", owner: "You", completed: false, priority: "medium" },
      { id: "k6", contactId: "10", source: "crm", title: "Follow up on pipe repair — Sunrise Apts", description: "Temporary fix on Unit 4B burst pipe. Schedule full repair with new copper fittings. Coordinate with tenant.", due: "2026-03-18", owner: "Lisa", completed: false, priority: "medium" },
      { id: "k7", contactId: "8", source: "crm", title: "Schedule site visit — Park kitchen remodel", description: "Helen wants a full kitchen gut renovation. Need to assess plumbing, electrical, and load-bearing walls.", due: "2026-03-20", owner: "Tom", completed: false, priority: "medium" },
      { id: "k8", contactId: "6", source: "crm", title: "Call Tamara about deck repair scope", description: "Tamara's deck has rotting joists. Determine if it's a repair or full rebuild, then prepare estimate.", due: "2026-03-19", owner: "Lisa", completed: false, priority: "low" },
      { id: "k9", contactId: "4", source: "crm", title: "Send invoice to Maria Santos", description: "Water heater install completed. Send final invoice for $2,800 including parts, labor, and permit fees.", due: "2026-03-14", owner: "You", completed: true, priority: "low" },
      { id: "k10", contactId: "1", source: "crm", title: "Order low-flow fixtures for Karen", description: "Karen picked the Moen Align series. Order faucet, showerhead, and toilet from plumbing supply.", due: "2026-03-15", owner: "You", completed: true, priority: "medium" },
    ],
    touchpoints: [
      { id: "t1", contactId: "1", type: "call", title: "Confirmed appointment", description: "Karen confirmed Thursday 9 AM for bathroom refit. Need to pick up fixtures and shut-off valve beforehand.", date: "Today, 3:00 PM", owner: "You" },
      { id: "t2", contactId: "2", type: "note", title: "Job progress update", description: "Panel upgrade 70% done. Old 100A panel removed, new 200A mounted. Wiring tomorrow, inspection Friday.", date: "Today, 11:00 AM", owner: "You" },
      { id: "t3", contactId: "10", type: "call", title: "Emergency call — burst pipe", description: "Unit 4B had a burst pipe under kitchen sink. Isolated water, temporary fix in place. Full repair tomorrow.", date: "Today, 8:30 AM", owner: "Lisa" },
      { id: "t4", contactId: "3", type: "meeting", title: "Site walkthrough", description: "Walked Dave's commercial space. 3 rooftop HVAC units need replacement. Quoted $6,200 for all three.", date: "Mar 15, 1:00 PM", owner: "Lisa" },
      { id: "t5", contactId: "5", type: "email", title: "Estimate sent", description: "Sent detailed roofing estimate for 8-unit complex. $8,500 for full replacement, $3,200 for patch repair.", date: "Mar 14, 2:00 PM", owner: "Tom" },
      { id: "t6", contactId: "7", type: "call", title: "AC consultation", description: "Mike wants central AC for 1,800 sq ft ranch. Recommended 3-ton split system. Install scheduled for next week.", date: "Mar 13, 10:00 AM", owner: "You" },
      { id: "t7", contactId: "4", type: "note", title: "Job completed", description: "Installed new kitchen faucet and garbage disposal. Customer very happy. Left review request card.", date: "Mar 12, 4:00 PM", owner: "You" },
      { id: "t8", contactId: "9", type: "call", title: "Job cancelled", description: "Greg decided to hold off on rewiring. Budget constraints. May revisit in summer.", date: "Mar 8, 11:00 AM", owner: "You" },
    ],
  },
];
